###############################################################
# Plot data generated by Kaifa MA304H3E AMS meter,            #
# and saved  to disk by Raspberry Pi.                         #
#                                                             #
# Plot shows voltage during one day and night (date).         #
# Note: MA304H3E only shows L1 and L2 with 230V mains.        #
###############################################################

import matplotlib.pyplot as plt
from datetime import datetime
import matplotlib.dates as md

def main(fileName, hour1, hour2):
  with open (fileName, "r") as fp:
    rwList = fp.readlines()
    
  spltList = []
  tmList = []
  vltList1 = []
  # vltList2 = []
  vltList3 = []

  for element in rwList:
    spltList.append(element.split(","))

  for element in spltList:
    tmString = element[0] + " " + element[1]
    tmObject = datetime.strptime(tmString, '%Y-%m-%d %H:%M:%S')

    # Select hours to display
    a = element[1][0:2]
    if int(a) >= int(hour1) and int(a) < int(hour2):
        tmList.append(tmObject)
        vltList1.append(int(element[12]))
        # vltList2.append(int(element[13]))
        vltList3.append(int(element[14]))

  fig = plt.figure()
  ax = fig.add_subplot(1,1,1)

  plt.title("AMS meter data " + spltList[0][0][:10])
  plt.xticks(rotation=90)

  ax.plot(tmList, vltList1, "b", label="Volt L1 x 10")
  # ax.plot(tmList, vltList2, "g", label="Volt L2 x 10")
  ax.plot(tmList, vltList3, "r", label="Volt L3 x 10")
  # ax.xaxis.set_major_formatter(md.DateFormatter("%Y-%m-%d"))
  ax.xaxis.set_major_formatter(md.DateFormatter("%H:%M:%S"))
  ax.grid(which='both')
  ax.legend()
  plt.show(block=False)

if __name__ == '__main__':
  main()
