#!/bin/bash

# This file should be run as a Cron job 10
# minutes after midnight.

# Copy files in /var/kaifalog/ to USB stick
cp /var/kaifalog/* /media/pi/D8AF-261F/

# Remove files older than 2 days in /var/kaifalog/
find /var/kaifalog/* -mtime +2 -exec rm {} \;
