###############################################################
# Plot current data generated by Kaifa MA304H3E AMS meter,    #
# saved to usb stick on Raspberry Pi.                         #
###############################################################

import matplotlib.pyplot as plt
from datetime import datetime
import matplotlib.dates as md

def main(fileName, hour1, hour2):
  with open (fileName, "r") as fp:
    rwList = fp.readlines()
    
  spltList = []
  tmList = []
  curList1 = []
  curList2 = []
  curList3 = []

  for element in rwList:
    spltList.append(element.split(","))

  for element in spltList:
    tmString = element[0] + " " + element[1]
    tmObject = datetime.strptime(tmString, '%Y-%m-%d %H:%M:%S')

    # Select hours to display
    a = element[1][0:2]
    if int(a) >= int(hour1) and int(a) < int(hour2):
        tmList.append(tmObject)
        curList1.append(int(element[9]))
        curList2.append(int(element[10]))
        curList3.append(int(element[11]))

  fig = plt.figure()
  ax = fig.add_subplot(1,1,1)

  ax.set_aspect(0.5)
  fig, ax = plt.subplots(figsize=(10,5))

  plt.title("AMS meter data " + spltList[0][0][:10])
  plt.xticks(rotation=90)

  ax.plot(tmList, curList1, "b", label="Current L1 x 1000")
  ax.plot(tmList, curList2, "g", label="Current L2 x 1000")
  ax.plot(tmList, curList3, "r", label="Current L3 x 1000")
  # ax.xaxis.set_major_formatter(md.DateFormatter("%Y-%m-%d"))
  ax.xaxis.set_major_formatter(md.DateFormatter("%H:%M:%S"))
  ax.grid(which='both')
  ax.legend()
  plt.savefig("currents.png", dpi=200, bbox_inches='tight')
  # plt.show(block=False)

if __name__ == '__main__':
  main()
