###############################################################
# Plot data generated by Kaifa MA304H3E AMS meter,            #
# and saved  to disk by Raspberry Pi.                         #
#                                                             #
# Plot shows active power during one day and night (date).    #
###############################################################

import matplotlib.pyplot as plt
from datetime import datetime
import matplotlib.dates as md

def main(fileName, hour1, hour2):
  with open (fileName, "r") as fp:
    rwList = fp.readlines()
    
  spltList = []
  tmList = []
  pwrList = []

  for element in rwList:
    spltList.append(element.split(","))

  for element in spltList:
    tmString = element[0] + " " + element[1]
    tmObject = datetime.strptime(tmString, '%Y-%m-%d %H:%M:%S')

    # Select hours to display
    a = element[1][0:2]
    if int(a) >= int(hour1) and int(a) < int(hour2):
        tmList.append(tmObject)
        pwrList.append(int(element[5]))

  fig = plt.figure()
  ax = fig.add_subplot(1,1,1)

  plt.title("AMS meter data " + spltList[0][0][:10])
  plt.xticks(rotation=90)

  ax.plot(tmList, pwrList, "b", label="Active power (W)")
  #ax.xaxis.set_major_formatter(md.DateFormatter("%Y-%m-%d"))
  ax.xaxis.set_major_formatter(md.DateFormatter("%H:%M:%S"))
  ax.grid(which='both')
  ax.legend()
  plt.show(block=False)

if __name__ == '__main__':
  main()
